name: CI para Proyecto Node.js

on:
  push:
    branches:
      - sanchez  # Cambia esto por la rama correcta si es necesario

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out el código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia esto a la versión correcta de Node.js para tu proyecto

      - name: Limpiar caché de npm
        run: npm cache clean --force

      - name: Eliminar node_modules
        run: rm -rf node_modules

      - name: Instalar dependencias
        run: npm install

      - name: Verificar instalación de Jest
        run: |
          if ! [ -x "$(command -v jest)" ]; then
            echo "Jest no está instalado correctamente";
            exit 1;
          fi

      - name: Ejecutar tests
        run: npm test
